In [1]:
import pandas as pd
df = pd.read_csv('../Data/netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [2]:
# mes films
mes_films = [
    "Histoire terrifiante", "Bird Box", "Mercredi ", "Stranger Things",
    "Frankenstein", "Army of the Dead", "Troll", "Sous la Seine", "Anaconda",
    "The Meg", "Sans un bruits", "Day Shift", "The Silence", 
    "Nobody Sleeps in the Woods Tonight", "Le Rituel", 
    "Personne ne sort d'ici vivant", "Monstre", "Dans les hautes herbes", 
    "Viking wolf", "Sweet Home"
]

# Filtrage automatique
selection = df[df['title'].isin(mes_films)]
print(f"On a trouvé {len(selection)} titres sur les {len(mes_films)} demandés.")
selection

On a trouvé 5 titres sur les 20 demandés.

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
853,s854,Movie,Army of the Dead,Zack Snyder,"Dave Bautista, Ella Purnell, Omari Hardwick, G...",United States,"May 21, 2021",2021,R,148 min,"Action & Adventure, Horror Movies","After a zombie outbreak in Las Vegas, a group ..."
1788,s1789,Movie,Nobody Sleeps in the Woods Tonight,Bartosz M. Kowalski,"Julia Wieniawa-Narkiewicz, Michał Lupa, Wiktor...",Poland,"October 28, 2020",2020,TV-MA,103 min,"Horror Movies, International Movies","Addicted to technology, a group of teens atten..."
3685,s3686,TV Show,Stranger Things,NaN,"Winona Ryder, David Harbour, Finn Wolfhard, Mi...",United States,"July 4, 2019",2019,TV-14,3 Seasons,"TV Horror, TV Mysteries, TV Sci-Fi & Fantasy","When a young boy vanishes, a small town uncove..."
3930,s3931,Movie,The Silence,John R. Leonetti,"Stanley Tucci, Kiernan Shipka, Miranda Otto, K...","Canada, Germany","April 10, 2019",2019,PG-13,91 min,"Horror Movies, Thrillers",With the world under attack by deadly creature...
4268,s4269,Movie,Bird Box,Susanne Bier,"Sandra Bullock, Trevante Rhodes, John Malkovic...",United States,"December 21, 2018",2018,R,124 min,"Dramas, Sci-Fi & Fantasy, Thrillers",Five years after an ominous unseen presence dr...

In [3]:
 
df_final = selection[['title', 'description', 'release_year']]
df_final.to_json('../Data/films_extraits.json', orient='records')

In [4]:
titres_trouves = selection['title'].tolist()
manquants = [f for f in mes_films if f not in titres_trouves]
print("Films à chercher sur IMDb :", manquants)

Films à chercher sur IMDb : ['Histoire terrifiante', 'Mercredi ', 'Frankenstein', 'Troll', 'Sous la Seine', 'Anaconda', 'The Meg', 'Sans un bruits', 'Day Shift', 'Le Rituel', "Personne ne sort d'ici vivant", 'Monstre', 'Dans les hautes herbes', 'Viking wolf', 'Sweet Home']

In [5]:
# Ta liste complète basée sur tes captures d'écran
mes_films = [
    "Scary Stories to Tell in the Dark", "Bird Box", "Wednesday", "Stranger Things",
    "Frankenstein", "Army of the Dead", "Troll", "Under Paris", "Anaconda",
    "The Meg", "A Quiet Place", "Day Shift", "The Silence", 
    "Nobody Sleeps in the Woods Tonight", "The Ritual", 
    "No One Gets Out Alive", "Monster", "In the Tall Grass", 
    "Viking Wolf", "Sweet Home"
]

# On filtre le CSV pour extraire ces films
selection = df[df['title'].isin(mes_films)]

# On affiche le nombre de films trouvés
print(f"Extraction réussie pour {len(selection)} films sur 20.")
selection

Extraction réussie pour 8 films sur 20.

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
853,s854,Movie,Army of the Dead,Zack Snyder,"Dave Bautista, Ella Purnell, Omari Hardwick, G...",United States,"May 21, 2021",2021,R,148 min,"Action & Adventure, Horror Movies","After a zombie outbreak in Las Vegas, a group ..."
910,s911,Movie,Monster,Anthony Mandler,"Kelvin Harrison Jr., Jennifer Hudson, Jeffrey ...",United States,"May 7, 2021",2021,TV-MA,99 min,Dramas,A talented teen implicated in a robbery-turned...
1788,s1789,Movie,Nobody Sleeps in the Woods Tonight,Bartosz M. Kowalski,"Julia Wieniawa-Narkiewicz, Michał Lupa, Wiktor...",Poland,"October 28, 2020",2020,TV-MA,103 min,"Horror Movies, International Movies","Addicted to technology, a group of teens atten..."
3450,s3451,Movie,In the Tall Grass,Vincenzo Natali,"Patrick Wilson, Laysla De Oliveira, Avery Whit...","Canada, United States","October 4, 2019",2019,TV-MA,102 min,"Horror Movies, Thrillers","After hearing a boy's cry for help, a pregnant..."
3685,s3686,TV Show,Stranger Things,NaN,"Winona Ryder, David Harbour, Finn Wolfhard, Mi...",United States,"July 4, 2019",2019,TV-14,3 Seasons,"TV Horror, TV Mysteries, TV Sci-Fi & Fantasy","When a young boy vanishes, a small town uncove..."
3930,s3931,Movie,The Silence,John R. Leonetti,"Stanley Tucci, Kiernan Shipka, Miranda Otto, K...","Canada, Germany","April 10, 2019",2019,PG-13,91 min,"Horror Movies, Thrillers",With the world under attack by deadly creature...
4268,s4269,Movie,Bird Box,Susanne Bier,"Sandra Bullock, Trevante Rhodes, John Malkovic...",United States,"December 21, 2018",2018,R,124 min,"Dramas, Sci-Fi & Fantasy, Thrillers",Five years after an ominous unseen presence dr...
5042,s5043,Movie,The Ritual,David Bruckner,"Rafe Spall, Arsher Ali, Robert James-Collier, ...","United Kingdom, Canada","February 9, 2018",2018,TV-MA,95 min,"Horror Movies, International Movies, Thrillers",Four friends with a long-standing – but strain...

In [6]:
df_final = selection[['title', 'description', 'release_year']]
df_final.to_json('../Data/films_extraits.json', orient='records')

In [7]:
titres_trouves = selection['title'].tolist()
manquants = [f for f in mes_films if f not in titres_trouves]
print("Films à chercher sur IMDb :", manquants)

Films à chercher sur IMDb : ['Scary Stories to Tell in the Dark', 'Wednesday', 'Frankenstein', 'Troll', 'Under Paris', 'Anaconda', 'The Meg', 'A Quiet Place', 'Day Shift', 'No One Gets Out Alive', 'Viking Wolf', 'Sweet Home']

In [8]:
# Étape 6 : Liste des films récupérés manuellement sur IMDb
films_manuels = [
    {"title": "Scary Stories to Tell in the Dark", "description": "Un groupe d'adolescents doivent affronter leurs peurs afin de survivre.", "release_year": 2019, "difficulty": "Évident/culte"},
    {"title": "Wednesday", "description": "Mercredi Addams tente de maîtriser ses capacités psychiques et de résoudre le mystère qui a impliqué ses parents.", "release_year": 2022, "difficulty": "Évident/culte"},
    {"title": "Frankenstein", "description": "Victor Frankenstein donne vie à une créature lors d'une expérience interdite.", "release_year": 2025, "difficulty": "Évident/culte"},
    {"title": "Troll", "description": "Une créature gigantesque se réveille après mille ans et détruit tout sur son passage vers Oslo.", "release_year": 2022, "difficulty": "Facile/accessible"},
    {"title": "Under Paris", "description": "Une scientifique doit faire face à son passé pour sauver Paris d'un requin géant dans la Seine.", "release_year": 2024, "difficulty": "Facile/accessible"},
    {"title": "Anaconda", "description": "Deux amis d'enfance voyagent au cœur de l'Amazonie pour tourner le remake de leur film préféré.", "release_year": 2025, "difficulty": "Facile/accessible"},
    {"title": "The Meg", "description": "Jonas Taylor doit surmonter ses peurs pour secourir des personnes prisonnières d'un requin de 23 mètres de long.", "release_year": 2018, "difficulty": "Facile/accessible"},
    {"title": "A Quiet Place", "description": "Une famille est forcée de vivre en silence pour se protéger de monstres à l'ouïe ultra-sensible.", "release_year": 2018, "difficulty": "Moyen/technique"},
    {"title": "Day Shift", "description": "Un père utilise son travail de nettoyage de piscine comme façade pour chasser et tuer des vampires.", "release_year": 2022, "difficulty": "Moyen/technique"},
    {"title": "No One Gets Out Alive", "description": "Une immigrante se retrouve prisonnière d'un cauchemar sans issue dans une pension.", "release_year": 2021, "difficulty": "Difficile/expert"},
    {"title": "Viking Wolf", "description": "Thale, 17 ans, vient d'emménager dans une petite ville après que sa mère a trouvé un nouveau boulot dans la police locale.", "release_year": 2022, "difficulty": "Difficile/expert"},
    {"title": "Sweet Home", "description": "Hyunsoo, un lycéen solitaire, emménage dans un ancien immeuble alors que des humains se transforment en monstres.", "release_year": 2020, "difficulty": "Difficile/expert"}
]

import pandas as pd
df_manuels = pd.DataFrame(films_manuels)
print(f"{len(df_manuels)} films ajoutés manuellement.")

12 films ajoutés manuellement.

In [9]:
# Fusion et calcul des points
resultat_final = pd.concat([df_final, df_manuels], ignore_index=True)

resultat_final['points'] = resultat_final['difficulty'].map({
    'Évident/culte': 5,
    'Facile/accessible': 10,
    'Moyen/technique': 20,
    'Difficile/expert': 30
})

print(f"Total de la liste : {len(resultat_final)} films.")

Total de la liste : 20 films.

In [10]:
import json

#  : Génération du fichier data/films.js
json_data = resultat_final.to_dict(orient='records')
with open('../data/films.js', 'w', encoding='utf-8') as f:
    f.write(f"const filmsData = {json.dumps(json_data, ensure_ascii=False, indent=4)};")

print("Fichier data/films.js généré ! ")

Fichier data/films.js généré !